spring.application.name=ms-productos

server.port=8081

#configuracion para la BD
spring.datasource.url=jdbc:mysql://localhost:3306/bd_productos
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#propiedades para logs (logback - SLF4J)
logging.level.com.diego.ms-productos=debug
#Es para todo lo que suceda en el framework de springboot en el jpa
logging.level.org.springframework=warn 
#Es para todo lo que suceda en el hibernate formato en sql de la BD
logging.level.hibernate.orm.jdbc.bind=debug
#Limita lo que se muestra en la consola
logging.level.root=warn

#Formato para cada linea de log en la consola
# %d -> fecha y hora
# [%5level] -> nivel (DEBUG-WARN-INFO-ERROR)
# %logger{30} -> nombre del elemento (clase) recortando a n caracteres
# %msg -> el mensaje que escribimos en el log.
# %n -> salto de linea
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%5level] %logger{30} - $msg%n

#Configurar guardado de los logs (persistencia de logs)
logging.file.name=logs/ms-productos.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
