services:

#Servicio 1: levantar MySQL
  mysql:
  #Levante una version especifica del mysql
    image: mysql:8.4
    #Nombre para este contenedor
    container_name: mysql-microservicios
    #Variables de entorno quen necesita mysql al iniciar
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_productos #Solo crea una, las demas se crean en el sql
    #init-db.sql solo se ejecuta la primera vez
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3307:3306"
    #Verficar que mysql este realmente listo antes antes de ejecutar lo demas
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 10s #Revisa cada 10 segundos
      timeout: 5s #Timeout por cada intento
      retries: 5 #Intentos antes de marcar como error
      start_period: 30s #Tiempo antes del primer intento
    networks:
      - microservicios-net

  #Servicio 2: eureka
  eureka-server:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: on-failure
    networks:
      - microservicios-net

  #Servicio 3: productos
  ms-productos:
    build:
      context: ./ms-productos
      dockerfile: Dockerfile
    container_name: ms-productos
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy #Espera que mysql este OK
      eureka-server:
        condition: service_started #Espera hasta que eureka este levantado
    restart: on-failure
    networks:
      - microservicios-net

  #Servicio 4: clientes
  ms-clientes:
    build:
      context: ./ms-clientes
      dockerfile: Dockerfile
    container_name: ms-clientes
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy #Espera que mysql este OK
      eureka-server:
        condition: service_started #Espera hasta que eureka este levantado
    restart: on-failure
    networks:
      - microservicios-net

  #Servicio 5: apigateway
  api-gateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_started #Espera hasta que eureka este levantado
      ms-productos:
        condition: service_started #Espera hasta que eureka este levantado
      ms-clientes:
        condition: service_started #Espera hasta que eureka este levantado
    restart: on-failure
    networks:
      - microservicios-net

#Almacenamiento pesistente
volumes:
  mysql-data:

#Crear la red virtual interna
networks:
  microservicios-net:
    driver: bridge