server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ruta-ms-productos
              uri: lb://ms-productos
              predicates:
                - Path=/api/productos,/api/productos/**
            - id: ruta-ms-clientes
              uri: lb://ms-clientes
              predicates:
                - Path=/api/clientes,/api/clientes/**
eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: api-gateway
    instance-id: api-gateway:${server.port}

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
            
